### ISSUE TITLE
Hi ✋

### ISSUE THREAD

**Issue by xgrons** [ImZaw/ImZaw#1]
i was wondering how did u get [api ](https://zawmedia-api.herokuapp.com/) working on heroku 
i'm making my own version of Selenium-less api , it working on my own machine since i have a arabic ip but when i host it it dosn't work because egybest don't work on foreign country

**Comment by ImZaw** [comment]
Europe would work

**Comment by xgrons** [comment]
well there is a free service deta.sh (always free) but it hosting in Germany wich is blocked
but u right i tested on heroku europe Ireland work fine

**Comment by ImZaw** [comment]
> well there is a free service deta.sh (always free) but it hosting in Germany wich is blocked but u right i tested on heroku europe Ireland work fine

replit is free too but its servers are probably in usa so nah, ill be using heroku swapping between two of them through the month
